[functions.auth-sms]
enabled = true
verify_jwt = true
import_map = "./functions/auth-sms/deno.json"
entrypoint = "./functions/auth-sms/index.ts"
[functions.notify-approval]
enabled = true
verify_jwt = true
import_map = "./functions/notify-approval/deno.json"
entrypoint = "./functions/notify-approval/index.ts"
[functions.sms-hook]
enabled = true
verify_jwt = false
import_map = "./functions/sms-hook/deno.json"
entrypoint = "./functions/sms-hook/index.ts"