android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process

org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon.idletimeout=120000

org.gradle.jvmargs=-Xmx700m -XX:MaxMetaspaceSize=500m -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.workers.max=1

android.builtInKotlin=false
android.newDsl=false