// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:google_maps_flutter/google_maps_flutter.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK7dRifiX0mtogUJknS-hfQIsFqWkD42M',
    appId: '1:279965298426:web:ffd1072dd9882a7f252343',
    messagingSenderId: '279965298426',
    projectId: 'gyanshalaapp',
    authDomain: 'gyanshalaapp.firebaseapp.com',
    storageBucket: 'gyanshalaapp.firebasestorage.app',
    measurementId: 'G-3RXSVS2TFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyv3xrSLH3LYGNlOVsdifWEbe0TIbX9E',
    appId: '1:279965298426:android:88dbf6efb9ebecc0252343',
    messagingSenderId: '279965298426',
    projectId: 'gyanshalaapp',
    storageBucket: 'gyanshalaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_SpnD8o_6sK3hrNmlxhkw9-iLRjm6qM',
    appId: '1:279965298426:ios:bd716e39593e645c252343',
    messagingSenderId: '279965298426',
    projectId: 'gyanshalaapp',
    storageBucket: 'gyanshalaapp.firebasestorage.app',
    iosBundleId: 'com.example.gyanshalaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_SpnD8o_6sK3hrNmlxhkw9-iLRjm6qM',
    appId: '1:279965298426:ios:bd716e39593e645c252343',
    messagingSenderId: '279965298426',
    projectId: 'gyanshalaapp',
    storageBucket: 'gyanshalaapp.firebasestorage.app',
    iosBundleId: 'com.example.gyanshalaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK7dRifiX0mtogUJknS-hfQIsFqWkD42M',
    appId: '1:279965298426:web:3b9b80b9c161ea43252343',
    messagingSenderId: '279965298426',
    projectId: 'gyanshalaapp',
    authDomain: 'gyanshalaapp.firebaseapp.com',
    storageBucket: 'gyanshalaapp.firebasestorage.app',
    measurementId: 'G-8LPZ33M0H5',
  );

  String streetViewUrl(LatLng pos) {
    const apiKey = "AIzaSyAWp-D51c0k4Df-HgN7BUD24nrR2pVc3Wg";
    return "https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${pos.latitude},${pos.longitude}&key=$apiKey";
  }
}
